var stringTable = {

//	{% if page == 'dashboard' %}
	fillInfoNotDone: "가입 신청이 완료되지 않았습니다.",
	goToFillInfo: '가입 신청 페이지로 이동하겠습니까?',
	noConcurrentUser: '활성 사용자가 존재하지 않습니다.',
	chatRequestToUser: '에게 대화요청을 하시겠습니까?',
	waitChatRequest: '응답을 기다리고 있습니다',
	chatRequestRejected: '님이 대화요청을 거절하였습니다.',
	chatRequestLeft: '님이 페이지에서 나갔습니다.',
	noChatURL: '실시간 대화항목이 개설되지 않았습니다.<br><br>컨텐츠 구성에서 실시간 대화를 추가 하시면 방문자에게 대화요청을 할 수 있습니다.',
	returningUser: '재 방문 사용자',
	newUser: '신규 방문 사용자',
	direct: '직접',
	minute: '분',
	maxConnectionNumber: '최대 접속자 수',
	connectionNumber: '접속자 수',
	minuteAgo: '분전',
	minutesAgo: '분전',
	secondsAgo: '초전',
	secondAgo: '초전',
	realTimeData: '실시간 데이터',
	now: '지금',
	visitorType: '방문자 타입',
	visitorNumber: '방문자 수',
	visitNumber: '방문 횟수',
	uniqueVisitor: '순 방문자',
	newVisitor: '신규 방문자',
	returningVisitor: '기존 방문자',
	visitRoute: '방문 경로',
	deviceType: '디바이스 타입',
	deviceNumber: '디바이스 수',
	mobile: '모바일',
	desktop: '데스크탑',
	tablet: '타블릿',
	location: '지역',
	pageView: '페이지 뷰',
	page: '페이지',
	accumulatedNumber: '누적 수',
	keyword: '키워드',
	previousMonth: '이전 달',
	nextMonth: '다음 달',
	today: '오늘',
	january: '1월',
	february: '2월',
	march: '3월',
	april: '4월',
	may: '5월',
	june: '6월',
	july: '7월',
	august: '8월',
	september: '9월',
	octorber: '10월',
	november: '11월',
	december: '12월',
	sunday: '일',
	monday: '월',
	tuesday: '화',
	wednesday: '수',
	thursday: '목',
	friday: '금',
	saturday: '토',
	visitorOnline: '온라인',
	visitorOffline: '오프라인',
	visitor:'손님',
	none: '없음',
	askPageEscape: "컨텐츠 작성 페이지에서 벗어나시겠습니까? <br><br><span style='color:red;'>주의: 작성하신 내용은 저장되지 않습니다.</span>",
	askSettingContentEscape: "컨텐츠 구성 페이지에서 이동하시겠습니까? <br><br><span style='color:red;'>주의: 저장하지 않은 변경사항은 반영되지 않습니다.</span>",
	counterpartIn: '대화 상대방이 다시 들어왔습니다',
	counterpartOut: '대화 상대방이 접속 종료를 하였습니다',
	leaveChatRoom: '대화방에서 상대방이 나갔습니다.',
	notInChatRoom: '상대방이 온라인 상태이나 대화방에 접속중이 아닙니다.<br><br>현재 머무르고 있는 페이지: <b>{0}</b>',
	sessionOut: '유효한 세션이 아닙니다.<br><br>다시 로그인 후 사용해주세요.',
	notExistPage: '존재하지 않는 페이지 입니다.',
	askPostMessage: "입력하신 내용을 등록하겠습니까?",
	askDelete: "삭제하시겠습니까?<br><br><span style='color:red;'>주의: 삭제된 건은 복구되지 않습니다.</span>",
	deleteLink: "선택한 노드를 삭제하시겠습니까?<br><br><span style='color:red;'>주의: 부모노드삭제시 하위노드 전부 삭제됩니다.</span>",
	notSelected: "항목이 선택되지 않았습니다.",
	uploadPicture: '사진 올리기',
	deletePicture: '선택한 사진을 삭제하시겠습니까?',
	nameNotProvided: '이름을 입력해 주세요.',
	subjectNotProvided: '제목을 4글자 이상 입력해 주세요.',
	bodyNotProvided: '내용을 입력해 주세요.',
	customInputNotProvided: '추가 항목에 내용을 입력해 주세요.',
	editSuccess: '정상적으로 수정되었습니다.',
	saveSuccess: '정상적으로 저장되었습니다.',
	registerSuccess: '정상적으로 등록되었습니다.',
	template: '템플릿',
	templateCar: '자동차 옵션',
	component: '컴포넌트',
	componentImage: '사진',
	componentMap: '지도',
    componentDaumMap: '지도(다음)',
	componentTextArea: '텍스트 영역',
	componentBox: '박스',
	componentSlideDocument: '슬라이드 (PPT, PDF)',
	componentSlidePicture: '슬라이드 (사진)',
	componentCombination: '컴포넌트 콤보',
	transparent: '투명',
	elementsize: '크기조정',
	editorAction: '작업',
	editorActionCopy: '복사',
	editorActionPaste: '붙여넣기',
	editorActionDelete: '삭제',
	editorActionTopSpace: '문서 상단 공간 생성',
	editorActionBottomSpace: '문서 하단 공간 생성',
	editorActionBackground: '문서 배경 설정',
	editorActionMapReboot: '지도 재기동',
	attributeSetup: '속성',
	pasteOnlyText: '텍스트만 붙여넣기 하시겠습니까?',
	unset: '설정안됨',
	width: '넓이',
	entireWidth: '모니터 전체',
	heightToParent: '부모 높이의',
	preview: '미리보기',
	htmlFile: 'HTML 파일',
	editor: '수동 에디터',
	writable: '쓰기 허용',
	notWritable: '쓰기 허용 안함',
	hide: '감추기',
	show: '보이기',
	save: '저장',
	askSave: '저장하시겠습니까?',
	productBoard: '상품 게시판',
	askBoard: '문의 게시판',
	normalBoard: '일반 게시판',
	fullWidth: '전체 넓이 (모니터 넓이)',
	contentWidth: '컨텐츠 넓이에 맞춤 (960px)',
	slideProcessing: "슬라이드 파일을 그림 파일로 변환중 입니다.<br>처리 시간은 약 1-3분 내외 입니다.<br>잠시만 기다려 주세요...<br><br><img src='/resources/images/progress_circle.gif' style='display:block; margin-left:auto; margin-right:auto; width:32px; height:32px;'>",
	pageFileUploadDone: '정상적으로 처리되었습니다.<br>반드시 저장을 하셔야 페이지에 반영이 됩니다.',
	slideDone: '슬라이드 파일 변환 작업이 완료되었습니다.',
	slideFailed: '죄송합니다.<br>슬라이드 파일 변환 중 에러가 발생하였습니다.',
	fileUploadProgress: '파일 업로드 중 입니다...',
	fileUploadDone: '파일 업로드가 완료 됐습니다.',
	reconnect: "서버와의 통신 상태가 좋지 않습니다.<br>인터넷 환경을 체크해 주세요.",
	pageDataTransmitted: "페이지 데이터 전송이 완료되었습니다.<br>아래 버튼을 눌르면 새 탭에서 페이지가 열립니다.<br><br>URL 만료까지 <span id='popup-timeout'>{0}</span> 초 남았습니다.<br><br><a href='{1}' target='_blank'><button class='general-popup-button btn nostyle-anchor move-to-preview-btn' style='height:40px;' onclick='{2}'>미리보기로 이동</button></a>",
	notImageComponent: '사진 컴포넌트만 설정 가능 합니다.',
	notSupportedComponent: '지원하지 않는 요소이거나 선택된 항목이 없습니다.',
	deleteSelected: '하이라이트된 영역 전체를 삭제하시겠습니까?',
	noCopied: '복사된 항목이 없습니다.',
	noMap: '선택 영역 내부에 지도가 존재하지 않습니다.',
	copied: '복사되었습니다.',
	pasteDone: '붙여넣기가 수행되었습니다.',
	boxHeightAdjust: '박스 높이 조정',
	stickyPost: '공지글',
	normalPost: '일반글',
	firstUploadBackgroundImage: '배경 이미지를 먼저 업로드 해주세요',

	duplicateKeyword: '중복된 키워드를 입력하셨습니다.',
	mobileSettingContent: '모바일 환경에선 해당 기능을 사용하는데 어려움이 있을 수 있습니다.',
	leavePage: '페이지에서 이동하시겠습니까? (저장하지 않은 내용은 반영되지 않습니다)',
	viewportRestricted: '해당 뷰포트에서는 지원하지 않습니다 <br>데스크탑 가로넓이 1000px 이상에서 이용해주세요.',
	loadingNotDone: '페이지 로딩이 완료되지 않았습니다.<br><br>잠시만 기다려 주세요...',

	selectItemSelf: '가장 바깥 (self)',
	selectItemEntireWidthContent: '전체 영역 내부 (960px)',
	selectItemMap: '지도',
	selectItemImage: '사진',
	selectItemBox: '박스',
	selectItemComponent: '컴포넌트',
	selectItemSlide: '슬라이드',
	selectItemIframe: '아이프레임',

	trialNotSupported: '체험 계정은 지원하지 않습니다.<br><br>가입 하시면 모든 기능을 사용하실 수 있습니다.<br>지금 가입 페이지로 이동하시겠습니까?',

//	{% endif %}

//	{% if page == 'signup' %}
	emailNotMatch: "이메일과 이메일 확인 값이 같지 않습니다.",
	fullnameLength: "이름은 2글자 이상으로 입력 해 주세요.",
	passwordLength: "비밀번호는 4글자 이상 16글자 이하로 설정 해 주세요.",
	passwordNotMatch: "비밀번호와 비밀번호 확인 값이 같지 않습니다.",
	emailExist: "같은 이메일을 사용하는 유저가 있습니다.",
	signupSuccess: "가입신청이 완료되었습니다.",
	agreeNotChecked: '이용약관, 개인정보 취급 방침 동의하셔야 가입 신청을 할 수 있습니다.',
//	{% endif %}

//	{% if page == 'fillinfo' or page == 'settings' %}
	fullnameLength: "이름은 2글자 이상으로 입력 해 주세요.",
	serviceNameLength: "서비스 이름은 2글자 이상으로 입력해주세요.",
	serviceTagLength: "서비스 태그명은 2글자 이상으로 입력해주세요.",
	serviceTagExist: "동일한 서비스 주소명이 존재합니다.",
	serviceCategoryEmpty: "서비스 분류를 선택 해 주세요",
	serviceLocationEmpty: "서비스 지역을 선택 해 주세요.",
	fillinfoDone: '상세 정보 입력이 완료되었습니다.',
	mobileAuth: '핸드폰 인증',
	mobileAuthMessage: " 번호로 인증번호를 보냈습니다.<br><span id='auth-remaining' style='color:green'>180</span>초 남음 <br><span id='auth-failed' style='display:none; color:red;'>인증실패: 입력한 번호를 다시한번 확인해주세요.</span>",
	mobileAuthTimeout: '인증가능 시간이 만료되었습니다.<br>다시 시도해 주세요',
	mobileAuthInvalidNumber: '인증번호 전송에 실패했습니다.<br>번호를 다시한번 확인 해주세요',
	mobileAuthDone: '인증성공',
	mobileAuthDoneMessage: '감사합니다<br>핸드폰 인증에 성공하였습니다.',
	mobileAuthNotDone: '핸드폰 인증이 완료되지 않았습니다.',
	use: '사용',
	noUse: '사용안함',
	createService: '서비스를 생성하시겠습니까?',
    saveServiceManagement: "<div style='color:#ff6600;'>(주의) 삭제한 서비스는 영구적으로 삭제가 됩니다.</div>",
    enterPassword: '아래 입력 항목에 비밀번호를 입력해주세요.',
    cantDeleteAllService: '남은 서비스 숫자는 하나 이상이어야 합니다.',
    cantDeleteActiveService: "활성화된 서비스는 삭제할 수 없습니다.",
    cancelDelete: "삭제취소",
    actionDelete: '삭제',
//	{% endif %}

	//{% if page == 'settings' %}
	changeSettingsDone: "설정 내용 변경이 적용되었습니다.",
	emailChanged: "변경된 이메일로 인증 요청 메일을 전송하였습니다.",
	emailExist: "같은 이메일을 사용하는 유저가 있습니다.",
	passwordLength: "비밀번호는 4글자 이상 16글자 이하로 설정 해 주세요.",
	passwordNotMatch: "비밀번호와 비밀번호 확인 값이 같지 않습니다.",
	extendUse: '사용기간 연장을 하시겠습니까?',
	pointSpentForExtending: '사용(기간연장)',
	receiveAccountInfo: '입금하실 계좌정보를 문자로 받아보시겠습니까?',
	sendAccountInfoDone: '입금하실 계좌정보를 고객님의 핸드폰으로 전송하였습니다.<br>감사합니다.',
	requestTransactionCheckDone: '정상적으로 접수되었습니다.<br>확인 후 바로 처리해 드리겠습니다.<br>감사합니다.',
	//{% endif %}

	//{% if page == 'login' %}
	resetPassword: '비밀번호 찾기',
	resetPasswordMessage: '가입하신 이메일 주소를 입력해 주세요.' + '<br>' + '비밀번호를 초기화 할 수 있는 링크를 보내드립니다.',
	resetPasswordEmailSuccess: '비밀번호 초기화를 위한 이메일을 발송하였습니다.<br>발송된 이메일에 포함된 링크는 12시간 동안 유효합니다.<br>한번 페이지에 방문하면 링크는 사용 만료가 됩니다.',
	passwordLength: '비밀번호는 4글자 이상입니다.',
	loginFail: '없는 아이디거나 비밀번호가 맞지 않습니다.',
	notRegisteredEmail: '등록되지 않은 이메일 주소 입니다.',
	//{% endif %}

	//{% if page == 'passwordreset' %}
	passwordLength: "비밀번호는 4글자 이상 16글자 이하로 설정 해 주세요.",
	passwordNotMatch: "비밀번호와 비밀번호 확인 값이 같지 않습니다.",
	passwordResetSuccess: '정상적으로 비밀번호 변경이 완료되었습니다.',
	//{% endif %}

	//{% if page == 'index' %}
	duplicateLogin: '같은 계정으로 중복 접근이 발생하여 해당 세션은 로그아웃 처리되었습니다.',
	//{% endif %}

	/* common */
	wrongPassword: '비밀번호가 맞지 않습니다.',
	invalidEmailFormat: "잘못된 이메일 형식입니다.",
	emailSendSuccess: '이메일 발송이 성공하였습니다.',
	internalError: "서버와의 통신이 실패하였습니다.",
	fillAllFields: "모든 필드의 입력을 완료 해 주세요",
	close: "닫기",
	ok: "확인",
	cancel: "취소",
	send: "보내기",
	yes: "예",
	no: "아니오",
	uploadFail: '파일 업로드가 정상적으로 완료되지 않았습니다',
	requestDone: '정상적으로 처리되었습니다.',
	requestError: '죄송합니다. 요청이 정상적으로 처리되지 않았습니다.',
	tryAgain: "다시 시도해 주세요",
	warningBeforeLeaving: "페이지 내에 완료되지 않은 작업이 있습니다.",
	wrongFileType: "올바르지 않은 파일 형식입니다.",
	fileSizeExceed: "허용된 파일 크기를 초과합니다.",
	logout: "로그아웃 하시겠습니까?",
	oldIENotSupported: "인터넷 익스플로러 8 미만은 지원하지 않습니다.",
	oldIEPreview: '인터넷 익스플로러 8 미만은 모바일에서 미리보기가 제대로 동작하지 않습니다.',
	expired: '사용이 만료되었습니다.<br><br>포인트를 사용하셔서 사용기간을 연장시켜주시기 바랍니다.',
	buffer: ''
};